# -*- coding: utf-8 -*-
"""todo_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NREkFBhTQ58KnIFGeDt7SO2iwG6jDeNA
"""

!pip install streamlit

!pip install streamlit pyngrok --quiet

!ngrok config add-authtoken $YOUR_AUTHTOKEN

!ngrok config add-authtoken 2yLqms5b66EN5uu0miWGO3lUzJI_9SLXRDM5aWrNwttiznsJ
code='''
import streamlit as st
#Title
st.title("To-Do'List Shrine")
st.subheader("Manage your day like a productivity princess!")
#Initialize session state for tasks
if "tasks" not in st.session_state:
  st.session_state.tasks=[]
#Add Tasks
new_task=st.text_input("➕ ADD A TASK")
if st.button("Add"):
  if new_task:
    st.session_state.tasks.append({'task':new_task,'done':False})
  else:
    st.warning("Task can't be empty!")
for i,task in enumerate(st.session_state.tasks):
  col1, col2, col3 = st.columns([6, 1, 1])
  with col1:
    checkbox = st.checkbox(task["task"], value=task["done"], key=i)
    st.session_state.tasks[i]["done"] = checkbox
  with col2:
    if st.button("✏️", key=f"edit_{i}"):
      edited = st.text_input("Edit task:", value=task["task"], key=f"edit_input_{i}")
      st.session_state.tasks[i]["task"] = edited
  with col3:
    if st.button("🗑️", key=f"delete_{i}"):
       st.session_state.tasks.pop(i)
       st.experimental_rerun()
       '''
with open('todo_app.py','w') as f:
  f.write(code)
from pyngrok import ngrok

# Kill previous tunnels if any
!kill $(lsof -t -i:8501)

# Open tunnel
public_url = ngrok.connect(addr='8501')
print("🚀 Streamlit App running at:", public_url)

# Launch Streamlit
!streamlit run todo_app.py &